package integralmontecarlo;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.nfunk.jep.ParseException;

/**
 *
 * @author hernan
 */
public class Integral extends javax.swing.JFrame {

    /**
     * Creates new form Integral
     */
    public Integral() {
        initComponents();
        setLocationRelativeTo(null);
        this.formatearTextFields();
        im = new MonteCarlo();
        this.jLabelEvaluando1.setText("");
        this.jLabelEvaluando2.setText("");
        this.jLabelEvaluando3.setText("");
        this.jLabelEvaluando4.setText("");
        this.jLabelEvaluando5.setText("");

        this.jLabelEvaluando1.setVisible(false);
        this.jLabelEvaluando2.setVisible(false);
        this.jLabelEvaluando3.setVisible(false);
        this.jLabelEvaluando4.setVisible(false);
        this.jLabelEvaluando5.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIntegralSimpleExpresion = new javax.swing.JTextField();
        jTextFieldIntegralSimpleB = new javax.swing.JTextField();
        jTextFieldIntegralSimpleA = new javax.swing.JTextField();
        jTextFieldIntegralSimplePuntos = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1IntegralSimpleAproximar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextField1SimpleValor = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField2SimpleError = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabelEvaluando1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldIntegralDobleB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIntegralDobleA = new javax.swing.JTextField();
        jTextFieldIntegralDobleD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIntegralDobleC = new javax.swing.JTextField();
        jTextFieldIntegralDobleExpresion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldIntegralDoblePuntos = new javax.swing.JTextField();
        jButton1IntegralDobleAproximar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField3DobleValor = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField2DobleError = new javax.swing.JTextField();
        jLabelEvaluando2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldIntegralTripleB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIntegralTripleA = new javax.swing.JTextField();
        jTextFieldIntegralTripleC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIntegralTripleD = new javax.swing.JTextField();
        jTextFieldIntegralTripleE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIntegralTripleF = new javax.swing.JTextField();
        jTextFieldIntegralTripleExpresion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldIntegralTriplePuntos = new javax.swing.JTextField();
        jButton1IntegralTripleAproximar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField5TripleValor = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField2TripleError = new javax.swing.JTextField();
        jLabelEvaluando3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldIntegralCuadrupleA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleB = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleD = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleF = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleG = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleH = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleExpresion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldIntegralCuadruplePuntos = new javax.swing.JTextField();
        jButton1IntegralCuadrupleAproximar = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jTextField5CuadrupleValor = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField2CuadrupleError = new javax.swing.JTextField();
        jLabelEvaluando4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldIntegralQuintupleA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleB = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleD = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleF = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleG = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleH = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleI = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleJ = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleExpresion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldIntegralQuintuplePuntos = new javax.swing.JTextField();
        jButton1IntegralQuintupleAproximar = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField5QuintupleValor = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField2QuintupleError = new javax.swing.JTextField();
        jLabelEvaluando5 = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1IntegralSimpleAproximar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aproximación de Integrales por método de Monte Carlo");
        setResizable(false);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel1.setText("∫");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("dx");

        jTextFieldIntegralSimpleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextFieldIntegralSimpleB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralSimpleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralSimpleBActionPerformed(evt);
            }
        });

        jTextFieldIntegralSimpleA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTextFieldIntegralSimplePuntos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setText("Puntos: ");

        jButton1IntegralSimpleAproximar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1IntegralSimpleAproximar.setText("Aproximar");
        jButton1IntegralSimpleAproximar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1IntegralSimpleAproximarMouseClicked(evt);
            }
        });
        jButton1IntegralSimpleAproximar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IntegralSimpleAproximarActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("Valor aproximado:  ");

        jTextField1SimpleValor.setEditable(false);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTextField2SimpleError.setEditable(false);

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel36.setText("Estimación del error: ");

        jLabelEvaluando1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEvaluando1.setText("Valor aproximado:  ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralSimpleA)
                            .addComponent(jTextFieldIntegralSimpleB)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralSimpleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelEvaluando1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1IntegralSimpleAproximar)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1SimpleValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2SimpleError, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralSimplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(401, 401, 401)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jTextFieldIntegralSimpleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralSimpleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntegralSimpleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIntegralSimplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(83, 83, 83)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1IntegralSimpleAproximar)
                    .addComponent(jLabel26)
                    .addComponent(jTextField1SimpleValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2SimpleError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(51, 51, 51)
                .addComponent(jLabelEvaluando1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(54, 54, 54))
        );

        jTabbedPane2.addTab("Integral simple", jPanel5);

        jTextFieldIntegralDobleB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralDobleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralDobleBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel3.setText("∫");

        jTextFieldIntegralDobleA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTextFieldIntegralDobleD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralDobleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralDobleDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel4.setText("∫");

        jTextFieldIntegralDobleC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTextFieldIntegralDobleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("dy dx");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setText("Puntos: ");

        jTextFieldIntegralDoblePuntos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jButton1IntegralDobleAproximar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1IntegralDobleAproximar.setText("Aproximar");
        jButton1IntegralDobleAproximar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IntegralDobleAproximarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setText("Valor aproximado:  ");

        jTextField3DobleValor.setEditable(false);

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setText("Estimación del error: ");

        jTextField2DobleError.setEditable(false);

        jLabelEvaluando2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEvaluando2.setText("Valor aproximado:  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluando2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1IntegralDobleAproximar)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3DobleValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2DobleError, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralDobleA)
                            .addComponent(jTextFieldIntegralDobleB)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralDobleC)
                            .addComponent(jTextFieldIntegralDobleD)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIntegralDobleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralDoblePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralDobleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIntegralDobleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralDobleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralDoblePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralDobleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralDobleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jTextField3DobleValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(jTextField2DobleError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1IntegralDobleAproximar))
                .addGap(51, 51, 51)
                .addComponent(jLabelEvaluando2)
                .addGap(31, 31, 31))
        );

        jTabbedPane2.addTab("Integral doble", jPanel1);

        jTextFieldIntegralTripleB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralTripleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralTripleBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel5.setText("∫");

        jTextFieldIntegralTripleA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jTextFieldIntegralTripleC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel6.setText("∫");

        jTextFieldIntegralTripleD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralTripleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralTripleDActionPerformed(evt);
            }
        });

        jTextFieldIntegralTripleE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel7.setText("∫");

        jTextFieldIntegralTripleF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralTripleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralTripleFActionPerformed(evt);
            }
        });

        jTextFieldIntegralTripleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("dz dy dx");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setText("Puntos: ");

        jTextFieldIntegralTriplePuntos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jButton1IntegralTripleAproximar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1IntegralTripleAproximar.setText("Aproximar");
        jButton1IntegralTripleAproximar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IntegralTripleAproximarActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setText("Valor aproximado:  ");

        jTextField5TripleValor.setEditable(false);

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setText("Estimación del error: ");

        jTextField2TripleError.setEditable(false);

        jLabelEvaluando3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEvaluando3.setText("Valor aproximado:  ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluando3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1IntegralTripleAproximar)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5TripleValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2TripleError, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralTripleA)
                            .addComponent(jTextFieldIntegralTripleB)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralTripleC)
                            .addComponent(jTextFieldIntegralTripleD)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralTripleE)
                            .addComponent(jTextFieldIntegralTripleF)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIntegralTripleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralTriplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralTripleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIntegralTripleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralTripleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralTriplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralTripleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralTripleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralTripleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralTripleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(jTextField5TripleValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)
                        .addComponent(jTextField2TripleError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1IntegralTripleAproximar))
                .addGap(51, 51, 51)
                .addComponent(jLabelEvaluando3)
                .addGap(24, 24, 24))
        );

        jTabbedPane2.addTab("Integral triple", jPanel2);

        jTextFieldIntegralCuadrupleA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel8.setText("∫");

        jTextFieldIntegralCuadrupleB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralCuadrupleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleBActionPerformed(evt);
            }
        });

        jTextFieldIntegralCuadrupleC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel9.setText("∫");

        jTextFieldIntegralCuadrupleD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralCuadrupleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleDActionPerformed(evt);
            }
        });

        jTextFieldIntegralCuadrupleE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel10.setText("∫");

        jTextFieldIntegralCuadrupleF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralCuadrupleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleFActionPerformed(evt);
            }
        });

        jTextFieldIntegralCuadrupleG.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel11.setText("∫");

        jTextFieldIntegralCuadrupleH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralCuadrupleH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleHActionPerformed(evt);
            }
        });

        jTextFieldIntegralCuadrupleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("du dz dy dx");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setText("Puntos: ");

        jTextFieldIntegralCuadruplePuntos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jButton1IntegralCuadrupleAproximar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1IntegralCuadrupleAproximar.setText("Aproximar");
        jButton1IntegralCuadrupleAproximar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IntegralCuadrupleAproximarActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel32.setText("Valor aproximado:  ");

        jTextField5CuadrupleValor.setEditable(false);

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel33.setText("Estimación del error: ");

        jTextField2CuadrupleError.setEditable(false);

        jLabelEvaluando4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEvaluando4.setText("Valor aproximado:  ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluando4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1IntegralCuadrupleAproximar)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5CuadrupleValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2CuadrupleError, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleA)
                            .addComponent(jTextFieldIntegralCuadrupleB)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleC)
                            .addComponent(jTextFieldIntegralCuadrupleD)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleE)
                            .addComponent(jTextFieldIntegralCuadrupleF)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleG)
                            .addComponent(jTextFieldIntegralCuadrupleH)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIntegralCuadrupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralCuadruplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIntegralCuadrupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralCuadrupleG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralCuadruplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralCuadrupleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralCuadrupleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralCuadrupleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jTextField5CuadrupleValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)
                        .addComponent(jTextField2CuadrupleError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1IntegralCuadrupleAproximar))
                .addGap(51, 51, 51)
                .addComponent(jLabelEvaluando4)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Integral cuádruple", jPanel3);

        jTextFieldIntegralQuintupleA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel12.setText("∫");

        jTextFieldIntegralQuintupleB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralQuintupleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleBActionPerformed(evt);
            }
        });

        jTextFieldIntegralQuintupleC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel13.setText("∫");

        jTextFieldIntegralQuintupleD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralQuintupleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleDActionPerformed(evt);
            }
        });

        jTextFieldIntegralQuintupleE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel14.setText("∫");

        jTextFieldIntegralQuintupleF.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralQuintupleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleFActionPerformed(evt);
            }
        });

        jTextFieldIntegralQuintupleG.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel15.setText("∫");

        jTextFieldIntegralQuintupleH.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralQuintupleH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleHActionPerformed(evt);
            }
        });

        jTextFieldIntegralQuintupleI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel16.setText("∫");

        jTextFieldIntegralQuintupleJ.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextFieldIntegralQuintupleJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleJActionPerformed(evt);
            }
        });

        jTextFieldIntegralQuintupleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("dw du dz dy dx  ");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setText("Puntos: ");

        jTextFieldIntegralQuintuplePuntos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jButton1IntegralQuintupleAproximar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1IntegralQuintupleAproximar.setText("Aproximar");
        jButton1IntegralQuintupleAproximar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IntegralQuintupleAproximarActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel34.setText("Valor aproximado:  ");

        jTextField5QuintupleValor.setEditable(false);

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel35.setText("Estimación del error: ");

        jTextField2QuintupleError.setEditable(false);

        jLabelEvaluando5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelEvaluando5.setText("Valor aproximado:  ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEvaluando5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1IntegralQuintupleAproximar)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5QuintupleValor, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2QuintupleError, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleA)
                            .addComponent(jTextFieldIntegralQuintupleB)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleC)
                            .addComponent(jTextFieldIntegralQuintupleD)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleE)
                            .addComponent(jTextFieldIntegralQuintupleF)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleG)
                            .addComponent(jTextFieldIntegralQuintupleH)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleI)
                            .addComponent(jTextFieldIntegralQuintupleJ)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralQuintuplePuntos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jTextFieldIntegralQuintupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(234, 234, 234))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralQuintupleJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextFieldIntegralQuintupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralQuintupleI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralQuintuplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralQuintupleH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralQuintupleG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralQuintupleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralQuintupleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralQuintupleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralQuintupleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralQuintupleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralQuintupleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(jTextField5QuintupleValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel35)
                        .addComponent(jTextField2QuintupleError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1IntegralQuintupleAproximar))
                .addGap(51, 51, 51)
                .addComponent(jLabelEvaluando5)
                .addGap(25, 25, 25))
        );

        jTabbedPane2.addTab("Integral quíntuple", jPanel4);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1248, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Históricos", jPanel6);

        jButton1IntegralSimpleAproximar1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1IntegralSimpleAproximar1.setText("Limpiar");
        jButton1IntegralSimpleAproximar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1IntegralSimpleAproximar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1IntegralSimpleAproximar1)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton1IntegralSimpleAproximar1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIntegralSimpleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralSimpleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralSimpleBActionPerformed

    private void jTextFieldIntegralDobleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralDobleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralDobleBActionPerformed

    private void jTextFieldIntegralDobleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralDobleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralDobleDActionPerformed

    private void jTextFieldIntegralTripleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralTripleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralTripleBActionPerformed

    private void jTextFieldIntegralTripleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralTripleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralTripleDActionPerformed

    private void jTextFieldIntegralTripleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralTripleFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralTripleFActionPerformed

    private void jTextFieldIntegralCuadrupleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleBActionPerformed

    private void jTextFieldIntegralCuadrupleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleDActionPerformed

    private void jTextFieldIntegralCuadrupleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleFActionPerformed

    private void jTextFieldIntegralCuadrupleHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleHActionPerformed

    private void jTextFieldIntegralQuintupleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleBActionPerformed

    private void jTextFieldIntegralQuintupleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleDActionPerformed

    private void jTextFieldIntegralQuintupleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleFActionPerformed

    private void jTextFieldIntegralQuintupleHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleHActionPerformed

    private void jTextFieldIntegralQuintupleJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleJActionPerformed

    private void jButton1IntegralSimpleAproximarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IntegralSimpleAproximarActionPerformed
        aproxSimple();
    }//GEN-LAST:event_jButton1IntegralSimpleAproximarActionPerformed

    private void jButton1IntegralQuintupleAproximarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IntegralQuintupleAproximarActionPerformed
        aproxQuintuple();
    }//GEN-LAST:event_jButton1IntegralQuintupleAproximarActionPerformed

    private void jButton1IntegralDobleAproximarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IntegralDobleAproximarActionPerformed
        aproxDoble();
    }//GEN-LAST:event_jButton1IntegralDobleAproximarActionPerformed

    private void jButton1IntegralSimpleAproximarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1IntegralSimpleAproximarMouseClicked

    }//GEN-LAST:event_jButton1IntegralSimpleAproximarMouseClicked

    private void jButton1IntegralTripleAproximarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IntegralTripleAproximarActionPerformed
        aproxTriple();
    }//GEN-LAST:event_jButton1IntegralTripleAproximarActionPerformed

    private void jButton1IntegralCuadrupleAproximarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IntegralCuadrupleAproximarActionPerformed
        aproxCuadruple();
    }//GEN-LAST:event_jButton1IntegralCuadrupleAproximarActionPerformed

    private void jButton1IntegralSimpleAproximar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1IntegralSimpleAproximar1ActionPerformed
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton1IntegralSimpleAproximar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1IntegralCuadrupleAproximar;
    private javax.swing.JButton jButton1IntegralDobleAproximar;
    private javax.swing.JButton jButton1IntegralQuintupleAproximar;
    private javax.swing.JButton jButton1IntegralSimpleAproximar;
    private javax.swing.JButton jButton1IntegralSimpleAproximar1;
    private javax.swing.JButton jButton1IntegralTripleAproximar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEvaluando1;
    private javax.swing.JLabel jLabelEvaluando2;
    private javax.swing.JLabel jLabelEvaluando3;
    private javax.swing.JLabel jLabelEvaluando4;
    private javax.swing.JLabel jLabelEvaluando5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1SimpleValor;
    private javax.swing.JTextField jTextField2CuadrupleError;
    private javax.swing.JTextField jTextField2DobleError;
    private javax.swing.JTextField jTextField2QuintupleError;
    private javax.swing.JTextField jTextField2SimpleError;
    private javax.swing.JTextField jTextField2TripleError;
    private javax.swing.JTextField jTextField3DobleValor;
    private javax.swing.JTextField jTextField5CuadrupleValor;
    private javax.swing.JTextField jTextField5QuintupleValor;
    private javax.swing.JTextField jTextField5TripleValor;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleA;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleB;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleC;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleD;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleE;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleExpresion;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleF;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleG;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleH;
    private javax.swing.JTextField jTextFieldIntegralCuadruplePuntos;
    private javax.swing.JTextField jTextFieldIntegralDobleA;
    private javax.swing.JTextField jTextFieldIntegralDobleB;
    private javax.swing.JTextField jTextFieldIntegralDobleC;
    private javax.swing.JTextField jTextFieldIntegralDobleD;
    private javax.swing.JTextField jTextFieldIntegralDobleExpresion;
    private javax.swing.JTextField jTextFieldIntegralDoblePuntos;
    private javax.swing.JTextField jTextFieldIntegralQuintupleA;
    private javax.swing.JTextField jTextFieldIntegralQuintupleB;
    private javax.swing.JTextField jTextFieldIntegralQuintupleC;
    private javax.swing.JTextField jTextFieldIntegralQuintupleD;
    private javax.swing.JTextField jTextFieldIntegralQuintupleE;
    private javax.swing.JTextField jTextFieldIntegralQuintupleExpresion;
    private javax.swing.JTextField jTextFieldIntegralQuintupleF;
    private javax.swing.JTextField jTextFieldIntegralQuintupleG;
    private javax.swing.JTextField jTextFieldIntegralQuintupleH;
    private javax.swing.JTextField jTextFieldIntegralQuintupleI;
    private javax.swing.JTextField jTextFieldIntegralQuintupleJ;
    private javax.swing.JTextField jTextFieldIntegralQuintuplePuntos;
    private javax.swing.JTextField jTextFieldIntegralSimpleA;
    private javax.swing.JTextField jTextFieldIntegralSimpleB;
    private javax.swing.JTextField jTextFieldIntegralSimpleExpresion;
    private javax.swing.JTextField jTextFieldIntegralSimplePuntos;
    private javax.swing.JTextField jTextFieldIntegralTripleA;
    private javax.swing.JTextField jTextFieldIntegralTripleB;
    private javax.swing.JTextField jTextFieldIntegralTripleC;
    private javax.swing.JTextField jTextFieldIntegralTripleD;
    private javax.swing.JTextField jTextFieldIntegralTripleE;
    private javax.swing.JTextField jTextFieldIntegralTripleExpresion;
    private javax.swing.JTextField jTextFieldIntegralTripleF;
    private javax.swing.JTextField jTextFieldIntegralTriplePuntos;
    // End of variables declaration//GEN-END:variables
    private MonteCarlo im;

    private void formatearTextFields() {
        RestrictedTextField restricted1 = new RestrictedTextField(this.jTextFieldIntegralSimpleA, "./eπ1234567890");
//        restricted1.setOnlyNums(true);
        restricted1.setLimit(5);
        RestrictedTextField restricted2 = new RestrictedTextField(this.jTextFieldIntegralSimpleB, "./eπ1234567890");
//        restricted2.setOnlyNums(true);
        restricted2.setLimit(5);

        RestrictedTextField restricted3 = new RestrictedTextField(this.jTextFieldIntegralDobleA, "./eπ1234567890");
//        restricted3.setOnlyNums(true);
        restricted3.setLimit(5);
        RestrictedTextField restricted4 = new RestrictedTextField(this.jTextFieldIntegralDobleB, "./eπ1234567890");
//        restricted4.setOnlyNums(true);
        restricted4.setLimit(5);
        RestrictedTextField restricted5 = new RestrictedTextField(this.jTextFieldIntegralDobleC, "./eπ1234567890");
//        restricted5.setOnlyNums(true);
        restricted5.setLimit(5);
        RestrictedTextField restricted6 = new RestrictedTextField(this.jTextFieldIntegralDobleD, "./eπ1234567890");
//        restricted6.setOnlyNums(true);
        restricted6.setLimit(5);

        RestrictedTextField restricted7 = new RestrictedTextField(this.jTextFieldIntegralTripleA, "./eπ1234567890");
//        restricted7.setOnlyNums(true);
        restricted7.setLimit(5);
        RestrictedTextField restricted8 = new RestrictedTextField(this.jTextFieldIntegralTripleB, "./1234567890");
//        restricted8.setOnlyNums(true);
        restricted8.setLimit(5);
        RestrictedTextField restricted9 = new RestrictedTextField(this.jTextFieldIntegralTripleC, "./eπ1234567890");
//        restricted9.setOnlyNums(true);
        restricted9.setLimit(5);
        RestrictedTextField restricted10 = new RestrictedTextField(this.jTextFieldIntegralTripleD, "./eπ1234567890");
//        restricted10.setOnlyNums(true);
        restricted10.setLimit(5);
        RestrictedTextField restricted11 = new RestrictedTextField(this.jTextFieldIntegralTripleE, "./eπ1234567890");
//        restricted11.setOnlyNums(true);
        restricted11.setLimit(5);
        RestrictedTextField restricted12 = new RestrictedTextField(this.jTextFieldIntegralTripleF, "./eπ1234567890");
//        restricted12.setOnlyNums(true);
        restricted12.setLimit(5);
        RestrictedTextField restricted13 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleA, "./eπ1234567890");
//        restricted13.setOnlyNums(true);
        restricted13.setLimit(5);
        RestrictedTextField restricted14 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleB, "./eπ1234567890");
//        restricted14.setOnlyNums(true);
        restricted14.setLimit(5);
        RestrictedTextField restricted15 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleC, "./eπ1234567890");
//        restricted15.setOnlyNums(true);
        restricted15.setLimit(5);
        RestrictedTextField restricted16 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleD, "./eπ1234567890");
//        restricted16.setOnlyNums(true);
        restricted16.setLimit(5);
        RestrictedTextField restricted17 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleE, "./eπ1234567890");
//        restricted17.setOnlyNums(true);
        restricted17.setLimit(5);
        RestrictedTextField restricted18 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleF, "./eπ1234567890");
//        restricted18.setOnlyNums(true);
        restricted18.setLimit(5);
        RestrictedTextField restricted19 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleG, "./eπ1234567890");
//        restricted19.setOnlyNums(true);
        restricted19.setLimit(5);
        RestrictedTextField restricted20 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleH, "./eπ1234567890");
//        restricted20.setOnlyNums(true);
        restricted20.setLimit(5);

        RestrictedTextField restrictedq = new RestrictedTextField(this.jTextFieldIntegralQuintupleA, "./eπ1234567890");
//        restrictedq.setOnlyNums(true);
        restrictedq.setLimit(5);
        RestrictedTextField restrictedw = new RestrictedTextField(this.jTextFieldIntegralQuintupleB, "./eπ1234567890");
//        restrictedw.setOnlyNums(true);
        restrictedw.setLimit(5);
        RestrictedTextField restrictede = new RestrictedTextField(this.jTextFieldIntegralQuintupleC, "./eπ1234567890");
//        restrictede.setOnlyNums(true);
        restrictede.setLimit(5);
        RestrictedTextField restrictedr = new RestrictedTextField(this.jTextFieldIntegralQuintupleD, "./eπ1234567890");
//        restrictedr.setOnlyNums(true);
        restrictedr.setLimit(5);
        RestrictedTextField restrictedt = new RestrictedTextField(this.jTextFieldIntegralQuintupleE, "./eπ1234567890");
//        restrictedt.setOnlyNums(true);
        restrictedt.setLimit(5);
        RestrictedTextField restrictedy = new RestrictedTextField(this.jTextFieldIntegralQuintupleF, "./eπ1234567890");
//        restrictedy.setOnlyNums(true);
        restrictedy.setLimit(5);
        RestrictedTextField restrictedu = new RestrictedTextField(this.jTextFieldIntegralQuintupleG, "./eπ1234567890");
//        restrictedu.setOnlyNums(true);
        restrictedu.setLimit(5);
        RestrictedTextField restrictedi = new RestrictedTextField(this.jTextFieldIntegralQuintupleH, "./eπ1234567890");
//        restrictedi.setOnlyNums(true);
        restrictedi.setLimit(5);
        RestrictedTextField restrictedo = new RestrictedTextField(this.jTextFieldIntegralQuintupleI, "./eπ1234567890");
//        restrictedo.setOnlyNums(true);
        restrictedo.setLimit(5);
        RestrictedTextField restrictedp = new RestrictedTextField(this.jTextFieldIntegralQuintupleJ, "./eπ1234567890");
//        restrictedp.setOnlyNums(true);
        restrictedp.setLimit(5);

        RestrictedTextField restricteds = new RestrictedTextField(this.jTextFieldIntegralSimplePuntos);
        restricteds.setOnlyNums(true);
        restricteds.setLimit(15);
        RestrictedTextField restrictedd = new RestrictedTextField(this.jTextFieldIntegralDoblePuntos);
        restrictedd.setOnlyNums(true);
        restrictedd.setLimit(15);
        RestrictedTextField restrictedf = new RestrictedTextField(this.jTextFieldIntegralTriplePuntos);
        restrictedf.setOnlyNums(true);
        restrictedf.setLimit(15);
        RestrictedTextField restrictedg = new RestrictedTextField(this.jTextFieldIntegralCuadruplePuntos);
        restrictedg.setOnlyNums(true);
        restrictedg.setLimit(5);
        RestrictedTextField restrictedh = new RestrictedTextField(this.jTextFieldIntegralQuintuplePuntos);
        restrictedh.setOnlyNums(true);
        restrictedh.setLimit(15);
    }

    private void aproxSimple() {
        try {
            String funcion = "";
            double a = 0.0;
            double b = 0.0;
            int n = 0;
            funcion = this.jTextFieldIntegralSimpleExpresion.getText();
            
            a = valorParametro(this.jTextFieldIntegralSimpleA.getText());
                    
            //a = Double.parseDouble(this.jTextFieldIntegralSimpleA.getText());
            b = Double.parseDouble(this.jTextFieldIntegralSimpleB.getText());
            n = Integer.parseInt(this.jTextFieldIntegralSimplePuntos.getText());
            Respuesta r = new Respuesta();
            r = im.monteCarloIntegralSimple(funcion, a, b, n);
            this.jLabelEvaluando1.setText("Listo");
            this.jTextField1SimpleValor.setText(r.getRespuesta());
            this.jTextField2SimpleError.setText(r.getEstimacionError());
            this.jTextArea1.setText(jTextArea1.getText() + r.getRespuestaConsola());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el análisis sintáctico", JOptionPane.ERROR_MESSAGE);
            System.out.println("ParseException: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("NumberFormatException: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("Exception: " + e.getMessage());
        }
    }

    private void aproxDoble() {
        try {
            String funcion = "";
            double a = 0.0;
            double b = 0.0;
            double c = 0.0;
            double d = 0.0;
            int n = 0;
            funcion = this.jTextFieldIntegralDobleExpresion.getText();
            a = Double.parseDouble(this.jTextFieldIntegralDobleA.getText());
            b = Double.parseDouble(this.jTextFieldIntegralDobleB.getText());
            c = Double.parseDouble(this.jTextFieldIntegralDobleC.getText());
            d = Double.parseDouble(this.jTextFieldIntegralDobleD.getText());
            n = Integer.parseInt(this.jTextFieldIntegralDoblePuntos.getText());
            Respuesta r = new Respuesta();
            r = im.monteCarloIntegralDoble(funcion, a, b, c, d, n);
            this.jLabelEvaluando2.setText("Listo");
            this.jTextField3DobleValor.setText(r.getRespuesta());
            this.jTextField2DobleError.setText(r.getEstimacionError());
            this.jTextArea1.setText(jTextArea1.getText() + r.getRespuestaConsola());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el análisis sintáctico", JOptionPane.ERROR_MESSAGE);
            System.out.println("ParseException: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("NumberFormatException: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("Exception: " + e.getMessage());
        }
    }

    private void aproxTriple() {
        try {
            String funcion = "";
            double a = 0.0;
            double b = 0.0;
            double c = 0.0;
            double d = 0.0;
            double e = 0.0;
            double f = 0.0;
            int n = 0;
            funcion = this.jTextFieldIntegralTripleExpresion.getText();
            a = Double.parseDouble(this.jTextFieldIntegralTripleA.getText());
            b = Double.parseDouble(this.jTextFieldIntegralTripleB.getText());
            c = Double.parseDouble(this.jTextFieldIntegralTripleC.getText());
            d = Double.parseDouble(this.jTextFieldIntegralTripleD.getText());
            e = Double.parseDouble(this.jTextFieldIntegralTripleE.getText());
            f = Double.parseDouble(this.jTextFieldIntegralTripleF.getText());
            n = Integer.parseInt(this.jTextFieldIntegralTriplePuntos.getText());
            Respuesta r = new Respuesta();
            r = im.monteCarloIntegralTriple(funcion, a, b, c, d, e, f, n);
            this.jLabelEvaluando3.setText("Listo");
            this.jTextField5TripleValor.setText(r.getRespuesta());
            this.jTextField2TripleError.setText(r.getEstimacionError());
            this.jTextArea1.setText(jTextArea1.getText() + r.getRespuestaConsola());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el análisis sintáctico", JOptionPane.ERROR_MESSAGE);
            System.out.println("ParseException: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("NumberFormatException: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("Exception: " + e.getMessage());
        }
    }

    private void aproxCuadruple() {
        try {
            String funcion = "";
            double a = 0.0;
            double b = 0.0;
            double c = 0.0;
            double d = 0.0;
            double e = 0.0;
            double f = 0.0;
            double g = 0.0;
            double h = 0.0;
            int n = 0;
            funcion = this.jTextFieldIntegralCuadrupleExpresion.getText();
            a = Double.parseDouble(this.jTextFieldIntegralCuadrupleA.getText());
            b = Double.parseDouble(this.jTextFieldIntegralCuadrupleB.getText());
            c = Double.parseDouble(this.jTextFieldIntegralCuadrupleC.getText());
            d = Double.parseDouble(this.jTextFieldIntegralCuadrupleD.getText());
            e = Double.parseDouble(this.jTextFieldIntegralCuadrupleE.getText());
            f = Double.parseDouble(this.jTextFieldIntegralCuadrupleF.getText());
            g = Double.parseDouble(this.jTextFieldIntegralCuadrupleG.getText());
            h = Double.parseDouble(this.jTextFieldIntegralCuadrupleH.getText());
            n = Integer.parseInt(this.jTextFieldIntegralCuadruplePuntos.getText());
            Respuesta r = new Respuesta();
            r = im.monteCarloIntegralCuadruple(funcion, a, b, c, d, e, f, g, h, n);
            this.jLabelEvaluando4.setText("Listo");
            this.jTextField5CuadrupleValor.setText(r.getRespuesta());
            this.jTextField2CuadrupleError.setText(r.getEstimacionError());
            this.jTextArea1.setText(jTextArea1.getText() + r.getRespuestaConsola());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el análisis sintáctico", JOptionPane.ERROR_MESSAGE);
            System.out.println("ParseException: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("NumberFormatException: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("Exception: " + e.getMessage());
        }
    }

    private void aproxQuintuple() {
        try {
            String funcion = "";
            double a = 0.0;
            double b = 0.0;
            double c = 0.0;
            double d = 0.0;
            double e = 0.0;
            double f = 0.0;
            double g = 0.0;
            double h = 0.0;
            double i = 0.0;
            double j = 0.0;
            int n = 0;
            funcion = this.jTextFieldIntegralQuintupleExpresion.getText();
            a = Double.parseDouble(this.jTextFieldIntegralQuintupleA.getText());
            b = Double.parseDouble(this.jTextFieldIntegralQuintupleB.getText());
            c = Double.parseDouble(this.jTextFieldIntegralQuintupleC.getText());
            d = Double.parseDouble(this.jTextFieldIntegralQuintupleD.getText());
            e = Double.parseDouble(this.jTextFieldIntegralQuintupleE.getText());
            f = Double.parseDouble(this.jTextFieldIntegralQuintupleF.getText());
            g = Double.parseDouble(this.jTextFieldIntegralQuintupleG.getText());
            h = Double.parseDouble(this.jTextFieldIntegralQuintupleH.getText());
            i = Double.parseDouble(this.jTextFieldIntegralQuintupleI.getText());
            j = Double.parseDouble(this.jTextFieldIntegralQuintupleJ.getText());
            n = Integer.parseInt(this.jTextFieldIntegralQuintuplePuntos.getText());
            Respuesta r = new Respuesta();
            r = im.monteCarloIntegralQuintuple(funcion, a, b, c, d, e, f, g, h, i, j, n);
            this.jLabelEvaluando5.setText("Listo");
            this.jTextField5QuintupleValor.setText(r.getRespuesta());
            this.jTextField2QuintupleError.setText(r.getEstimacionError());
            this.jTextArea1.setText(jTextArea1.getText() + r.getRespuestaConsola());
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el análisis sintáctico", JOptionPane.ERROR_MESSAGE);
            System.out.println("ParseException: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("NumberFormatException: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error durante el ingreso de datos", JOptionPane.ERROR_MESSAGE);
            System.out.println("Exception: " + e.getMessage());
        }
    }

    private double valorParametro(String valor) throws NumberFormatException{
        double resultado = 0.0;
        boolean cambio = false;
        if (valor.equals("e") == false) {
            resultado = 2.718281828459045;
            cambio = true;
        }
        if (valor.equals("π") == false) {
            resultado = 3.141592653589793;
            cambio = true;
        }
        if (!cambio) {
            resultado = Double.parseDouble(valor);
        }
        return resultado;
    }
}
