package integralmontecarlo;

import Atxy2k.CustomTextField.RestrictedTextField;

/**
 *
 * @author hernan
 */
public class Integral extends javax.swing.JFrame {

    /**
     * Creates new form Integral
     */
    public Integral() {
        initComponents();
        setLocationRelativeTo(null);
        this.formatearTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIntegralSimpleExpresion = new javax.swing.JTextField();
        jTextFieldIntegralSimpleB = new javax.swing.JTextField();
        jTextFieldIntegralSimpleA = new javax.swing.JTextField();
        jTextFieldIntegralSimplePuntos = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1IntegralSimpleAproximar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldIntegralDobleB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIntegralDobleA = new javax.swing.JTextField();
        jTextFieldIntegralDobleD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIntegralDobleC = new javax.swing.JTextField();
        jTextFieldIntegralDobleExpresion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldIntegralDoblePuntos = new javax.swing.JTextField();
        jButton1IntegralDobleAproximar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldIntegralTripleB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIntegralTripleA = new javax.swing.JTextField();
        jTextFieldIntegralTripleC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIntegralTripleD = new javax.swing.JTextField();
        jTextFieldIntegralTripleE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIntegralTripleF = new javax.swing.JTextField();
        jTextFieldIntegralTripleExpresion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldIntegralTriplePuntos = new javax.swing.JTextField();
        jButton1IntegralTripleAproximar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldIntegralCuadrupleA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleB = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleD = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleF = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleG = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldIntegralCuadrupleH = new javax.swing.JTextField();
        jTextFieldIntegralCuadrupleExpresion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldIntegralCuadruplePuntos = new javax.swing.JTextField();
        jButton1IntegralCuadrupleAproximar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldIntegralQuintupleA = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleB = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleD = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleE = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleF = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleG = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleH = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleI = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldIntegralQuintupleJ = new javax.swing.JTextField();
        jTextFieldIntegralQuintupleExpresion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldIntegralQuintuplePuntos = new javax.swing.JTextField();
        jButton1IntegralQuintupleAproximar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aproximación de Integrales por método de Monte Carlo");
        setResizable(false);

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel1.setText("∫");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("dx");

        jTextFieldIntegralSimpleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTextFieldIntegralSimpleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralSimpleBActionPerformed(evt);
            }
        });

        jLabel21.setText("Puntos: ");

        jButton1IntegralSimpleAproximar.setText("Aproximar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1IntegralSimpleAproximar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralSimpleA)
                            .addComponent(jTextFieldIntegralSimpleB)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIntegralSimpleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralSimplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addContainerGap(688, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jTextFieldIntegralSimpleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralSimpleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIntegralSimpleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIntegralSimplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(83, 83, 83)
                .addComponent(jButton1IntegralSimpleAproximar)
                .addGap(108, 108, 108))
        );

        jTabbedPane2.addTab("Integral simple", jPanel5);

        jTextFieldIntegralDobleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralDobleBActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel3.setText("∫");

        jTextFieldIntegralDobleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralDobleDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel4.setText("∫");

        jTextFieldIntegralDobleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("dy dx");

        jLabel22.setText("Puntos: ");

        jButton1IntegralDobleAproximar.setText("Aproximar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1IntegralDobleAproximar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralDobleA)
                            .addComponent(jTextFieldIntegralDobleB)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralDobleC)
                            .addComponent(jTextFieldIntegralDobleD)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIntegralDobleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralDoblePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralDobleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIntegralDobleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralDobleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralDoblePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralDobleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralDobleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addComponent(jButton1IntegralDobleAproximar)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Integral doble", jPanel1);

        jTextFieldIntegralTripleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralTripleBActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel5.setText("∫");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel6.setText("∫");

        jTextFieldIntegralTripleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralTripleDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel7.setText("∫");

        jTextFieldIntegralTripleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralTripleFActionPerformed(evt);
            }
        });

        jTextFieldIntegralTripleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setText("dz dy dx");

        jLabel23.setText("Puntos: ");

        jButton1IntegralTripleAproximar.setText("Aproximar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1IntegralTripleAproximar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralTripleA)
                            .addComponent(jTextFieldIntegralTripleB)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralTripleC)
                            .addComponent(jTextFieldIntegralTripleD)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralTripleE)
                            .addComponent(jTextFieldIntegralTripleF)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldIntegralTripleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralTriplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralTripleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIntegralTripleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralTripleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralTriplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralTripleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralTripleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralTripleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralTripleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addComponent(jButton1IntegralTripleAproximar)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Integral triple", jPanel2);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel8.setText("∫");

        jTextFieldIntegralCuadrupleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleBActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel9.setText("∫");

        jTextFieldIntegralCuadrupleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel10.setText("∫");

        jTextFieldIntegralCuadrupleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleFActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel11.setText("∫");

        jTextFieldIntegralCuadrupleH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralCuadrupleHActionPerformed(evt);
            }
        });

        jTextFieldIntegralCuadrupleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setText("du dz dy dx");

        jLabel24.setText("Puntos: ");

        jButton1IntegralCuadrupleAproximar.setText("Aproximar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1IntegralCuadrupleAproximar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleA)
                            .addComponent(jTextFieldIntegralCuadrupleB)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleC)
                            .addComponent(jTextFieldIntegralCuadrupleD)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleE)
                            .addComponent(jTextFieldIntegralCuadrupleF)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralCuadrupleG)
                            .addComponent(jTextFieldIntegralCuadrupleH)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIntegralCuadrupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralCuadruplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIntegralCuadrupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralCuadrupleG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralCuadruplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralCuadrupleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralCuadrupleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralCuadrupleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralCuadrupleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83)
                .addComponent(jButton1IntegralCuadrupleAproximar)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Integral cuádruple", jPanel3);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel12.setText("∫");

        jTextFieldIntegralQuintupleB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleBActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel13.setText("∫");

        jTextFieldIntegralQuintupleD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleDActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel14.setText("∫");

        jTextFieldIntegralQuintupleF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleFActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel15.setText("∫");

        jTextFieldIntegralQuintupleH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleHActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 100)); // NOI18N
        jLabel16.setText("∫");

        jTextFieldIntegralQuintupleJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIntegralQuintupleJActionPerformed(evt);
            }
        });

        jTextFieldIntegralQuintupleExpresion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel20.setText("dw du dz dy dx  ");

        jLabel25.setText("Puntos: ");

        jButton1IntegralQuintupleAproximar.setText("Aproximar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1IntegralQuintupleAproximar)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleA)
                            .addComponent(jTextFieldIntegralQuintupleB)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleC)
                            .addComponent(jTextFieldIntegralQuintupleD)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleE)
                            .addComponent(jTextFieldIntegralQuintupleF)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleG)
                            .addComponent(jTextFieldIntegralQuintupleH)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldIntegralQuintupleI)
                            .addComponent(jTextFieldIntegralQuintupleJ)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldIntegralQuintupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIntegralQuintuplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralQuintupleJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextFieldIntegralQuintupleExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntegralQuintupleI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntegralQuintuplePuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldIntegralQuintupleH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntegralQuintupleG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralQuintupleF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralQuintupleE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralQuintupleD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralQuintupleC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextFieldIntegralQuintupleB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldIntegralQuintupleA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(83, 83, 83)
                .addComponent(jButton1IntegralQuintupleAproximar)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Integral quíntuple", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIntegralSimpleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralSimpleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralSimpleBActionPerformed

    private void jTextFieldIntegralDobleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralDobleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralDobleBActionPerformed

    private void jTextFieldIntegralDobleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralDobleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralDobleDActionPerformed

    private void jTextFieldIntegralTripleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralTripleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralTripleBActionPerformed

    private void jTextFieldIntegralTripleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralTripleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralTripleDActionPerformed

    private void jTextFieldIntegralTripleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralTripleFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralTripleFActionPerformed

    private void jTextFieldIntegralCuadrupleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleBActionPerformed

    private void jTextFieldIntegralCuadrupleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleDActionPerformed

    private void jTextFieldIntegralCuadrupleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleFActionPerformed

    private void jTextFieldIntegralCuadrupleHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralCuadrupleHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralCuadrupleHActionPerformed

    private void jTextFieldIntegralQuintupleBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleBActionPerformed

    private void jTextFieldIntegralQuintupleDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleDActionPerformed

    private void jTextFieldIntegralQuintupleFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleFActionPerformed

    private void jTextFieldIntegralQuintupleHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleHActionPerformed

    private void jTextFieldIntegralQuintupleJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIntegralQuintupleJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIntegralQuintupleJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Integral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Integral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1IntegralCuadrupleAproximar;
    private javax.swing.JButton jButton1IntegralDobleAproximar;
    private javax.swing.JButton jButton1IntegralQuintupleAproximar;
    private javax.swing.JButton jButton1IntegralSimpleAproximar;
    private javax.swing.JButton jButton1IntegralTripleAproximar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleA;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleB;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleC;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleD;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleE;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleExpresion;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleF;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleG;
    private javax.swing.JTextField jTextFieldIntegralCuadrupleH;
    private javax.swing.JTextField jTextFieldIntegralCuadruplePuntos;
    private javax.swing.JTextField jTextFieldIntegralDobleA;
    private javax.swing.JTextField jTextFieldIntegralDobleB;
    private javax.swing.JTextField jTextFieldIntegralDobleC;
    private javax.swing.JTextField jTextFieldIntegralDobleD;
    private javax.swing.JTextField jTextFieldIntegralDobleExpresion;
    private javax.swing.JTextField jTextFieldIntegralDoblePuntos;
    private javax.swing.JTextField jTextFieldIntegralQuintupleA;
    private javax.swing.JTextField jTextFieldIntegralQuintupleB;
    private javax.swing.JTextField jTextFieldIntegralQuintupleC;
    private javax.swing.JTextField jTextFieldIntegralQuintupleD;
    private javax.swing.JTextField jTextFieldIntegralQuintupleE;
    private javax.swing.JTextField jTextFieldIntegralQuintupleExpresion;
    private javax.swing.JTextField jTextFieldIntegralQuintupleF;
    private javax.swing.JTextField jTextFieldIntegralQuintupleG;
    private javax.swing.JTextField jTextFieldIntegralQuintupleH;
    private javax.swing.JTextField jTextFieldIntegralQuintupleI;
    private javax.swing.JTextField jTextFieldIntegralQuintupleJ;
    private javax.swing.JTextField jTextFieldIntegralQuintuplePuntos;
    private javax.swing.JTextField jTextFieldIntegralSimpleA;
    private javax.swing.JTextField jTextFieldIntegralSimpleB;
    private javax.swing.JTextField jTextFieldIntegralSimpleExpresion;
    private javax.swing.JTextField jTextFieldIntegralSimplePuntos;
    private javax.swing.JTextField jTextFieldIntegralTripleA;
    private javax.swing.JTextField jTextFieldIntegralTripleB;
    private javax.swing.JTextField jTextFieldIntegralTripleC;
    private javax.swing.JTextField jTextFieldIntegralTripleD;
    private javax.swing.JTextField jTextFieldIntegralTripleE;
    private javax.swing.JTextField jTextFieldIntegralTripleExpresion;
    private javax.swing.JTextField jTextFieldIntegralTripleF;
    private javax.swing.JTextField jTextFieldIntegralTriplePuntos;
    // End of variables declaration//GEN-END:variables

private void formatearTextFields(){
        RestrictedTextField restricted1 = new RestrictedTextField(this.jTextFieldIntegralSimpleA);
        restricted1.setOnlyNums(true);
        restricted1.setLimit(5);
        RestrictedTextField restricted2 = new RestrictedTextField(this.jTextFieldIntegralSimpleB);
        restricted2.setOnlyNums(true);
        restricted2.setLimit(5);
       
   
        RestrictedTextField restricted3 = new RestrictedTextField(this.jTextFieldIntegralDobleA);
        restricted3.setOnlyNums(true);
        restricted3.setLimit(5);     
        RestrictedTextField restricted4 = new RestrictedTextField(this.jTextFieldIntegralDobleB);
        restricted4.setOnlyNums(true);
        restricted4.setLimit(5);  
        RestrictedTextField restricted5 = new RestrictedTextField(this.jTextFieldIntegralDobleC);
        restricted5.setOnlyNums(true);
        restricted5.setLimit(5);      
        RestrictedTextField restricted6 = new RestrictedTextField(this.jTextFieldIntegralDobleD);
        restricted6.setOnlyNums(true);
        restricted6.setLimit(5);


        RestrictedTextField restricted7 = new RestrictedTextField(this.jTextFieldIntegralTripleA);
        restricted7.setOnlyNums(true);
        restricted7.setLimit(5); 
        RestrictedTextField restricted8 = new RestrictedTextField(this.jTextFieldIntegralTripleB);
        restricted8.setOnlyNums(true);
        restricted8.setLimit(5);
        RestrictedTextField restricted9 = new RestrictedTextField(this.jTextFieldIntegralTripleC);
        restricted9.setOnlyNums(true);
        restricted9.setLimit(5);
        RestrictedTextField restricted10 = new RestrictedTextField(this.jTextFieldIntegralTripleD);
        restricted10.setOnlyNums(true);
        restricted10.setLimit(5);
        RestrictedTextField restricted11 = new RestrictedTextField(this.jTextFieldIntegralTripleE);
        restricted11.setOnlyNums(true);
        restricted11.setLimit(5);
        RestrictedTextField restricted12 = new RestrictedTextField(this.jTextFieldIntegralTripleF);
        restricted12.setOnlyNums(true);
        restricted12.setLimit(5);



        RestrictedTextField restricted13 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleA);
        restricted13.setOnlyNums(true);
        restricted13.setLimit(5); 
        RestrictedTextField restricted14 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleB);
        restricted14.setOnlyNums(true);
        restricted14.setLimit(5);
        RestrictedTextField restricted15 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleC);
        restricted15.setOnlyNums(true);
        restricted15.setLimit(5);
        RestrictedTextField restricted16 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleD);
        restricted16.setOnlyNums(true);
        restricted16.setLimit(5);
        RestrictedTextField restricted17 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleE);
        restricted17.setOnlyNums(true);
        restricted17.setLimit(5);
        RestrictedTextField restricted18 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleF);
        restricted18.setOnlyNums(true);
        restricted18.setLimit(5);
         RestrictedTextField restricted19 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleG);
        restricted19.setOnlyNums(true);
        restricted19.setLimit(5);
        RestrictedTextField restricted20 = new RestrictedTextField(this.jTextFieldIntegralCuadrupleH);
        restricted20.setOnlyNums(true);
        restricted20.setLimit(5);


        
        RestrictedTextField restrictedq = new RestrictedTextField(this.jTextFieldIntegralQuintupleA);
        restrictedq.setOnlyNums(true);
        restrictedq.setLimit(5);
        RestrictedTextField restrictedw = new RestrictedTextField(this.jTextFieldIntegralQuintupleB);
        restrictedw.setOnlyNums(true);
        restrictedw.setLimit(5);
        RestrictedTextField restrictede = new RestrictedTextField(this.jTextFieldIntegralQuintupleC);
        restrictede.setOnlyNums(true);
        restrictede.setLimit(5);
        RestrictedTextField restrictedr = new RestrictedTextField(this.jTextFieldIntegralQuintupleD);
        restrictedr.setOnlyNums(true);
        restrictedr.setLimit(5);
        RestrictedTextField restrictedt = new RestrictedTextField(this.jTextFieldIntegralQuintupleE);
        restrictedt.setOnlyNums(true);
        restrictedt.setLimit(5);
        RestrictedTextField restrictedy = new RestrictedTextField(this.jTextFieldIntegralQuintupleF);
        restrictedy.setOnlyNums(true);
        restrictedy.setLimit(5);
        RestrictedTextField restrictedu = new RestrictedTextField(this.jTextFieldIntegralQuintupleG);
        restrictedu.setOnlyNums(true);
        restrictedu.setLimit(5);
        RestrictedTextField restrictedi = new RestrictedTextField(this.jTextFieldIntegralQuintupleH);
        restrictedi.setOnlyNums(true);
        restrictedi.setLimit(5);
        RestrictedTextField restrictedo = new RestrictedTextField(this.jTextFieldIntegralQuintupleI);
        restrictedo.setOnlyNums(true);
        restrictedo.setLimit(5);
        RestrictedTextField restrictedp = new RestrictedTextField(this.jTextFieldIntegralQuintupleJ);
        restrictedp.setOnlyNums(true);
        restrictedp.setLimit(5);

        RestrictedTextField restricteds = new RestrictedTextField(this.jTextFieldIntegralSimplePuntos);
        restricteds.setOnlyNums(true);
        restricteds.setLimit(15);     
        RestrictedTextField restrictedd = new RestrictedTextField(this.jTextFieldIntegralDoblePuntos);
        restrictedd.setOnlyNums(true);
        restrictedd.setLimit(15);  
        RestrictedTextField restrictedf = new RestrictedTextField(this.jTextFieldIntegralTriplePuntos);
        restrictedf.setOnlyNums(true);
        restrictedf.setLimit(15);      
        RestrictedTextField restrictedg = new RestrictedTextField(this.jTextFieldIntegralCuadruplePuntos);
        restrictedg.setOnlyNums(true);
        restrictedg.setLimit(5);
        RestrictedTextField restrictedh = new RestrictedTextField(this.jTextFieldIntegralQuintuplePuntos,".1234567890");
//        restrictedh.setOnlyNums(true);
        restrictedh.setLimit(15);
}


}
