/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integralmontecarlo;

/**
 *
 * @author hernan
 */
public class NewJFrame extends javax.swing.JFrame {

    private int posicion = 0;

    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("√");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("^");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton11.setText("(");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText(")");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("<");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("*");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("/");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton14.setText("+");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton30.setText("<<");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton1.setText("w");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton31.setText("u");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("z");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setText("y");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setText("x");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton14)
                .addGap(5, 5, 5)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12)
                .addGap(27, 27, 27)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton30)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton34)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2)
                .addComponent(jButton3)
                .addComponent(jButton11)
                .addComponent(jButton12)
                .addComponent(jButton13)
                .addComponent(jButton14)
                .addComponent(jButton15)
                .addComponent(jButton16)
                .addComponent(jButton17)
                .addComponent(jButton30)
                .addComponent(jButton1)
                .addComponent(jButton31)
                .addComponent(jButton32)
                .addComponent(jButton33)
                .addComponent(jButton34))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton10.setText("ln");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setText("log");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton7.setText("sen");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("cos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("tan");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton35.setText("arcsen");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        jButton36.setText("arccos");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.setText("arctan");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton37)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton35)
                .addComponent(jButton36)
                .addComponent(jButton37))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton7)
                .addComponent(jButton4)
                .addComponent(jButton8)
                .addComponent(jButton10)
                .addComponent(jButton9))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton18.setText("0");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("1");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("2");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("3");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("4");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setText("5");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setText("6");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("7");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("8");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setText("9");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setText(".");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton5.setText("π");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("e");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton18)
                .addComponent(jButton19)
                .addComponent(jButton20)
                .addComponent(jButton21)
                .addComponent(jButton22)
                .addComponent(jButton23)
                .addComponent(jButton24)
                .addComponent(jButton25)
                .addComponent(jButton26)
                .addComponent(jButton27)
                .addComponent(jButton28)
                .addComponent(jButton5)
                .addComponent(jButton6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "√";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "√" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "√";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "^";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "^" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "^";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "π";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "π" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "π";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "e";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "e" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "e";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "cos";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "cos" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "cos";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "ln";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "ln" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 2;
            } else {
                cadena = cadena + "ln";
                posicion = posicion + 2;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "4";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "4" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "4";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "7";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "7" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "7";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "8";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "8" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "8";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "9";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "9" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "9";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        posicion = jTextField1.getCaretPosition();
        System.out.println("FocusLost - posicion: " + posicion);
    }//GEN-LAST:event_jTextField1FocusLost

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        posicion = jTextField1.getCaretPosition();
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "0";
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "0" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;

            } else {
                cadena = cadena + "0";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "1";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "1" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "1";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "2";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "2" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "2";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "3";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "3" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "3";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "5";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "5" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "5";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "6";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "6" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "6";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + ".";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "." + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + ".";
                posicion = posicion + 1;
            }
        }

        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        posicion = jTextField1.getCaretPosition();
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "+";
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "+" + cadena.substring(posicion, cadena.length());
            } else {
                cadena = cadena + "+";
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "-";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "-" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "-";
                posicion = posicion + 1;
            }
        }

        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "*";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "*" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "*";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "/";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "/" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "/";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "log";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "log" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "log";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "(";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "(" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "(";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + ")";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + ")" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + ")";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        posicion = jTextField1.getCaretPosition();
        System.out.println("FocusGained - posicion: " + posicion);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        this.jTextField1.setText("");
        this.posicion = 0;
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "sen";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "sen" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "sen";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "w";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "w" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "w";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "tan";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "tan" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "tan";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "u";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "u" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "u";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "z";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "z" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "z";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "y";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "y" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "y";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "x";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "x" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 1;
            } else {
                cadena = cadena + "x";
                posicion = posicion + 1;
            }
        }
        this.jTextField1.setText(cadena);    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        posicion = jTextField1.getCaretPosition();
        String cadena = this.jTextField1.getText().trim();
        System.out.println("cadena.length(): " + cadena.length());
        System.out.println("ActionPerformed - ActionPerformed borrar: " + posicion);

        if (cadena.length() > 0) {
            char charPosi = cadena.charAt(cadena.length() - 1);
            System.out.println("charPosi: " + charPosi);
            if (posicion == 0) {
                System.out.println("1111111111111111111111111111");
                if (cadena.length() > 0) {
                    System.out.println("222222222222222");

                    cadena = cadena.substring(0, cadena.length() - 1);
                    posicion = posicion - 2;
                    if (posicion < 0) {
                        posicion = 0;
                    }

                }
            } else {
                System.out.println("333333333333333333333");

                if (cadena.length() > 2) {
                    System.out.println("444444444444444");

                    cadena = cadena.substring(0, posicion - 1) + "" + cadena.substring(posicion, cadena.length());
                    posicion = posicion - 2;
                    if (posicion < 0) {
                        posicion = 0;
                    }

                } else {
                    cadena = cadena.substring(0, cadena.length() - 1);
                    System.out.println("444444444444444444444444444");

                }
                posicion = posicion - 2;
                if (posicion < 0) {
                    posicion = 0;
                }
            }
            this.jTextField1.setText(cadena);
        } else {
            posicion = 0;
    }//GEN-LAST:event_jButton13ActionPerformed
    }


    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "arcsen";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "arcsen" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "arcsen";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "arccos";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "arccos" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "arccos";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        posicion = jTextField1.getCaretPosition();
        System.out.println("ActionPerformed - ActionPerformed: " + posicion);
        String cadena = this.jTextField1.getText();
        if (posicion == 0) {
            cadena = cadena + "arctan";
            //posicion = posicion + 1;
        } else {
            if (cadena.length() > 1) {
                cadena = cadena.substring(0, posicion) + "arctan" + cadena.substring(posicion, cadena.length());
                posicion = posicion + 3;
            } else {
                cadena = cadena + "arctan";
                posicion = posicion + 3;
            }
        }
        this.jTextField1.setText(cadena);
    }//GEN-LAST:event_jButton37ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

}
